[package]
name = "forester-rs"
description = "Workflow framework based on the behavior trees"
authors = ["BorisZhguchev <zhguchev@hotmail.com>"]
homepage = "https://github.com/besok/forester"
repository = "https://github.com/besok/forester"
version = "0.5.1"
edition = "2021"
license-file = "LICENSE"
rust-version = "1.88"

[dependencies]
parsit = "0.2.1"
graphviz-rust = "0.9.8"
logos = "0.16.1"
itertools = "0.15.0"
strum = { version = "0.28.0", features = [] }
strum_macros = "0.28.0"
log = "0.4"
env_logger = "0.11.11"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151" }
serde_yaml = "0.9.34"
reqwest = { version = "0.13", features = ["blocking", "json"] }
tracing = "0.1"
axum = "0.7.9"
tokio = { version = "1.53.1", features = ["full"] }
tokio-util = "0.7.19"
chrono = "0.4.45"
quick-xml = "0.39.4"

tungstenite = { version = "0.29.0", features = ["url"] }
url = "2.5.8"
utoipa = { version = "5.5.0", features = ["axum_extras"] }

[dev-dependencies]
wiremock = "0.6.5"
forester-http = "0.1.0"
pretty_assertions = "1.4.1"
